temp = "hehe hehe hehe hehe hehe orewa Monkey D Dragon"
# ~~~~~~~~~~~~~Karix API's~~~~~~~~~~~~~~~~~~~~
MTALKZ_CALLPATCH_URL = "http://vcm.httpapi.zone/voiceapi/c2c.php"
MTALKZ_VOICE_OBD_OTP = "http://voice.httpapi.zone:9501/voiceapi/api_otp.php"
KARIX_WABA_API = "https://rcmapi.instaalerts.zone/services/rcm/sendMessage"


# ~~~~~~~~~~~~~SMARTFLOW API's~~~~~~~~~~~~~~~~
MTALKZ_SMARTFLOW_CALLPATCH_URL = "https://api-smartflo.tatateleservices.com/v1/click_to_call"
MTALKZ_SMARTFLOW_CREATE_AGENT_URL = "https://api-smartflo.tatateleservices.com/v1/agent"
MTALKZ_SMARTFLOW_CREATE_BROADCAST_URL = "https://api-smartflo.tatateleservices.com/v1/broadcast"
MTALKZ_SMARTFLOW_START_BROADCAST_URL = "https://api-smartflo.tatateleservices.com/v1/broadcast/start/"
MTALKZ_SMARTFLOW_PAUSE_BROADCAST_URL = "https://api-smartflo.tatateleservices.com/v1/broadcast/pause/"
MTALKZ_SMARTFLOW_RESUME_BROADCAST_URL = "https://api-smartflo.tatateleservices.com/v1/broadcast/resume/"
MTALKZ_SMARTFLOW_END_BROADCAST_URL = "https://api-smartflo.tatateleservices.com/v1/broadcast/end/"
MTALKZ_SMARTFLOW_CREATE_LEAD_LIST_URL = "https://api-smartflo.tatateleservices.com/v1/broadcast/list"
MTALKZ_SMARTFLOW_FETCH_LEAD_LIST_URL = "https://api-smartflo.tatateleservices.com/v1/broadcast/lists"
MTALKZ_SMARTFLOW_UPDATE_LEAD_LIST_URL = "https://api-smartflo.tatateleservices.com/v1/broadcast/list/"
MTALKZ_SMARTFLOW_DELETE_LEAD_LIST_URL = "https://api-smartflo.tatateleservices.com/v1/broadcast/list/"
MTALKZ_SMARTFLOW_ENTER_LEAD_IN_LEAD_LIST_URL = "https://api-smartflo.tatateleservices.com/v1/broadcast/leads/"
MTALKZ_SMARTFLOW_FETCH_ALL_IVR = "https://api-smartflo.tatateleservices.com/v1/ivrs"
MTALKZ_SMARTFLOW_CREATE_IVR = "https://api-smartflo.tatateleservices.com/v1/ivr"
MTALKZ_SMARTFLOW_FETCH_ALL_AUTO_ATTENDANTS = "https://api-smartflo.tatateleservices.com/v1/auto_attendants"
MTALKZ_SMARTFLOW_FETCH_AUTO_ATTENDANTS = "https://api-smartflo.tatateleservices.com/v1/auto_attendant/"
MTALKZ_SMARTFLOW_CREATE_AUTO_ATTENDANTS = "https://api-smartflo.tatateleservices.com/v1/auto_attendant"
MTALKZ_SMARTFLOW_GET_LEAD_ID = "https://api-smartflo.tatateleservices.com/v1/broadcast/leads/"
MTALKZ_SMARTFLOW_UPDATE_LEAD = "https://api-smartflo.tatateleservices.com/v1/broadcast/lead/"
MTALKZ_SMARTFLOW_DELETE_LEAD_URL = "https://api-smartflo.tatateleservices.com/v1/broadcast/lead/"
MTALKZ_SMARTFLOW_PANEL_LOGIN_FOR_TOKEN = "https://api-smartflo.tatateleservices.com/v1/auth/login"
MTALKZ_SMARTFLOW_REFERSH_TATA_TELE_TOKEN = "https://api-smartflo.tatateleservices.com/v1/auth/refresh"
MTALKZ_SMARTFLOW_FETCH_ALL_RECORDING = "https://api-smartflo.tatateleservices.com/v1/recordings"
MTALKZ_SMARTFLOW_DELETE_IVR = "https://api-smartflo.tatateleservices.com/v1/ivr/"
MTALKZ_SMARTFLOW_CALL_RECORD = "https://api-smartflo.tatateleservices.com/v1/call/records?did_numbers=" 
MTALKZ_FETCH_LEAD_FROM__LEAD_LIST = "https://api-smartflo.tatateleservices.com/v1/broadcast/leads/"